fix(context): store property missing from `useStoreApi`
pmndrs/zustand pull request #1258
Opened 2022-09-03 17:00 UTC by exuanbo

## Related Issues

Fixes #.

## Summary

When the store is created with persist middleware, property `storeApi.persist` is missing, which does not match its type.

The internal function `useBoundStore` should be named as `useContextStore`, because the store API is not assigned to it.

## Check List

- [x] `yarn run prettier` for formatting code and docs

2022-09-04 00:44 UTC, dai-shi approved these changes
Oh, nice catch! Both are valid points. Thanks for the fixes!

2022-09-05 13:58 UTC, dbritto-dev requested changes

2022-09-05 13:58 UTC, dbritto-dev commented on src/context.ts
> +    return useMemo<WithoutCallSignature<S>>(() => ({ ...store }), [store])
If you want to return all the props in the store, would be better just return the store directly

```suggestion
    return useMemo<WithoutCallSignature<S>>(() => store, [store])
```

2022-09-06 20:34 UTC, Himself65 commented
when can this PR land?

2022-09-06 22:26 UTC, dai-shi commented
[v4.1.2](https://github.com/pmndrs/zustand/milestone/7) is currently planned at Sep 12.

Feel free to use the codesandbox build until then.
https://ci.codesandbox.io/status/pmndrs/zustand/pr/1258
Find "Local Install Instructions" ☝️

2022-09-18 23:51 UTC, dai-shi commented
> v4.1.2 is currently planned at Sep 12.

Sorry for the delay. We would like to merge another change, which is taking some more time.
Please use the codesandbox build meanwhile.

2022-10-09 01:10 UTC, merged