Update persisting-store-data.md
pmndrs/zustand pull request #1267
Opened 2022-09-06 17:21 UTC by guymoon

## Related Issues

Fixes #1254

## Summary

Reviewed the following documentation:

- Location of added content
- typescript
- custom storage is connected Hash url usage 

## Check List

- [x] `yarn run prettier` for formatting code and docs

2022-09-06 22:24 UTC, dai-shi requested changes
Thanks for working on it. Can you create a new md file in docs/guides/?
I haven't looked it closely, but one comment is: Can you add a codesandbox link for a working example?

2022-09-07 04:23 UTC, guymoon commented
okay! thank u for comment.

2022-09-07 12:15 UTC, guymoon commented
Reviewed the following documentation:

- nav number of docs/guides/connect-to-state-with-url-hash.md 
- code sandbox demo

2022-09-08 09:33 UTC, dai-shi approved these changes
LGTM
Thanks for your contribution!

2022-09-08 09:33 UTC, merged