fix(docs): comparison
pmndrs/zustand pull request #1284
Opened 2022-09-10 19:34 UTC by dbritto-dev

## Related Issues

Fixes #1008 

## Summary

Adding some improvements to comparison docs

## Check List

- [x] `yarn run prettier` for formatting code and docs

2022-09-10 22:59 UTC, dai-shi approved these changes
LGTM. Anyone else wants to review?

2022-09-15 14:08 UTC, dbritto-dev commented
@chrisk-7777 @callumcrichton @Exalted100 what you think folks?

2022-09-15 14:27 UTC, callumcrichton commented on docs/getting-started/comparison.md
> +optimizations through atom dependency. While Zustand it is recommended that you
Line 323: However, with Zustand it is recommended that you ...

2022-09-15 14:29 UTC, callumcrichton requested changes
Line 323: "However, with Zustand it is recommended that you ..." something along those lines would make more sense. 👍

2022-09-15 14:38 UTC, dbritto-dev commented
@callumcrichton done

2022-09-20 00:39 UTC, dbritto-dev commented
@chrisk-7777 @bjornstar would you mind reviewing this PR?

2022-09-20 01:21 UTC, Exalted100 approved these changes

2022-09-20 01:24 UTC, Exalted100 commented
@dbritto-dev just checked and it looks fine to me. Although I would personally prefer active statements like "we recommend..." over passive ones like "it is recommended..." However, it's fine either way.

2022-09-20 01:31 UTC, bjornstar commented on docs/getting-started/comparison.md
> +  setCount: (countCallback: (count: State['count']) => State['count']) => void
```suggestion
  updateCount: (countCallback: (count: State['count']) => State['count']) => void
```

2022-09-20 01:43 UTC, dbritto-dev commented
@bjornstar @Exalted100 done

2022-09-20 01:44 UTC, bjornstar approved these changes
lgtm

2022-09-20 01:58 UTC, merged