relax react types
pmndrs/zustand pull request #1589
Opened 2023-01-31 14:41 UTC by lukesmurray

## Summary

`UseBoundStore` strictly enforces the shape of the `setState` function but does not rely on the shape of the `setState` function internally.

## Why we should be relaxed about `setState`

I want to define a middleware that makes the action in `devtools` required (to improve debugging store mutations in a large app). But if I make the third argument to `setState` required, the modified `setState` function is no longer compatible with the default `setState` function.

We get the following error message (edited for readability).

```
Types of property 'setState' are incompatible.

'<A extends string | { type: unknown; }>(
   partial: T | Partial<T> | ((state: T) => T | Partial<T>), 
   replace: boolean | undefined, 
   action: A
) => void' 

is not assignable to 

'(partial: unknown, replace?: boolean | undefined) => void'.
```

Internally the `react` extension only seems to rely on `getState` and `subscribe`, so I made that explicit in the types.

## Check List

- [x] `yarn run prettier` for formatting code and docs

2023-01-31 14:53 UTC, dai-shi commented
I don't think this is correct, or helps anyways. We do use `setState` on useBoundStore.
Have you made your vanilla store type correctly?
Are you already familiar with typing simpler middleware?

Closing. You can continue discussion here or open a new discussion.

2023-01-31 19:11 UTC, lukesmurray commented
Thank you for the prompt response and for creating and maintaining zustand!

- The `useStore` code doesn't seem to access `setState`. Is there something I'm missing? If `useBoundStore` uses `setState` then this change is definitely wrong and the issue should be closed.

https://github.com/pmndrs/zustand/blob/ab4118d395e3cd65a26eb53b639ac0616b270c51/src/react.ts#L33-L47

- I'm new to typing middleware but I'm pretty sure the middleware is correctly typed. Here is an [example with the error](https://stackblitz.com/edit/vitejs-vite-groma2?file=src/App.tsx). If we can relax `setState` using the changes I proposed the error would go away since the middleware would be allowed to overwrite `setState` to be a function that is incompatible with the vanilla `setState` call.

Here is an image of the error in case it doesn't show up for you but I assume it will.

![CleanShot 2023-01-31 at 14 03 50](https://user-images.githubusercontent.com/34020210/215858328-f9a28245-dd52-4fbd-930a-6d3b3092e504.png)

2023-02-01 02:48 UTC, dai-shi commented
> If `useBoundStore` uses `setState` then this change is definitely wrong and the issue should be closed.

The user can use it. See: https://tsplay.dev/wQYPvw
<img width="908" alt="image" src="https://user-images.githubusercontent.com/490574/215932185-e0dcbf0b-953b-4f7a-8786-902e0f53e1d5.png">


> I'm new to typing middleware but I'm pretty sure the middleware is correctly typed. Here is an [example with the error](https://stackblitz.com/edit/vitejs-vite-groma2?file=src/App.tsx).

Hmm, interesting.
We may need to ask @devanshj for help.
Here's the same one as stackblitz: https://tsplay.dev/N5O1MW
(We may need to make the type bivariant??)

2023-02-01 12:16 UTC, devanshj commented
> I'm pretty sure the middleware is correctly typed

Your `WithDevtoolsReq<StoreApi<T>>` is not a subtype of `StoreApi<T>`, so there's a very good chance the middleware typings are incorrect. Could you please share a minimal repro on TypeScript playground with your middleware typings.

Technically we could not ask for the `setState` as we don't use it in the implementation (the users would still be able to use `setState`) but in general it's not a good practice to fine-grain types to such an extent. In the worst case we could do that but that's not needed here.

2023-02-01 12:25 UTC, devanshj commented
To save me from manually diffing could you tell me in what way is your `devtoolsReq` different from `devtools`? Because the code compiles using `devtools` instead of `devtoolsReq`.

2023-02-01 12:30 UTC, lukesmurray commented
only difference is the action is required instead of optional. 

devtools has 
(...skipTwo, action?: A)

devtoolsReq has 
(...skipTwo, action: A)

2023-02-01 12:32 UTC, devanshj commented
Yeah I too just got that diff. So assuming it's an intended change, we'd need fine-grained type to allow passing a store with such middleware.

In that case we can reopen this PR.

2023-02-01 12:37 UTC, devanshj reviewed
Instead of this let's do...
```ts
type ReadonlyStoreApi<T> =
  Pick<StoreApi<T>, "getState" | "subscribe">
```

And then remove the constraint on `S` in `WithReact` (it's an internal type so it's okay) and then instead of `WithReact<StoreApi<unknown>>` we'd write `WithReact<ReadonlyStoreApi<unknown>>`. And same change for implementation type `WithReact<StoreApi<TState>>`.

2023-02-01 12:38 UTC, lukesmurray commented
sounds good I'll update the PR.

2023-02-01 12:44 UTC, dai-shi commented
Does this https://tsplay.dev/wQYPvw still work with the change?

2023-02-01 12:45 UTC, lukesmurray commented
yes. i'll upload an example stackblitz with that as well or can add it to the typings test if you prefer.

2023-02-01 12:47 UTC, lukesmurray commented
the proposed change only enforces the type of getState and subscribe. All other properties are passed through, including setState and other modifications to the store from other middleware.

2023-02-01 12:48 UTC, dai-shi commented
I see, it's the base type (`extends ...`). Yeah, please add tests.

2023-02-01 12:48 UTC, devanshj commented
> Does this https://tsplay.dev/wQYPvw still work with the change?

Yes, we're not changing the `create` type.

2023-02-01 13:03 UTC, devanshj reviewed
Let's also widen the constraint on `S` in `UseBoundStore` to a readonly store.

And perhaps we should widen the deprecated overload on `create`.

2023-03-02 01:08 UTC, dai-shi requested changes
@lukesmurray Can you please follow @devanshj 's suggestions?

2023-03-02 01:37 UTC, lukesmurray commented
yes i’ll submit tomorrow.

On Wed, Mar 1, 2023 at 8:08 PM Daishi Kato ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @lukesmurray <https://github.com/lukesmurray> Can you please follow
> @devanshj <https://github.com/devanshj> 's suggestions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pmndrs/zustand/pull/1589#pullrequestreview-1320897192>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDRW4VB3C6KWYNGE3RGFRLWZ7XJDANCNFSM6AAAAAAUMQT3SQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-04 16:26 UTC, lukesmurray commented
@dai-shi I've updated the PR. thank you for your patience

2023-03-05 01:41 UTC, dai-shi approved these changes
LGTM! Thanks for working on it.

Will merge when we prepare a next release.

2023-03-06 04:59 UTC, merged