docs: Update third-party-libraries.md
pmndrs/zustand pull request #1624
Opened 2023-02-13 02:56 UTC by AwesomeDevin

Update third-party-libraries：
- zustand-vue - State management for vue (Vue3 / Vue2) based on zustand. 
- zustand-pub - Cross-Application/Cross-Framework State Management And Sharing based on zustand and zustand-vue for React/Vue.

2023-02-13 03:33 UTC, dai-shi requested changes
Thanks. Can you put them in the alphabetical order?

2023-02-13 05:39 UTC, AwesomeDevin commented
> alphabetical order

OK

2023-02-13 05:46 UTC, AwesomeDevin commented
> Thanks. Can you put them in the alphabetical order?

it’s done~

2023-02-13 06:00 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
>  - [zustand-querystring](https://github.com/nitedani/zustand-querystring) — A Zustand middleware that syncs the store with the querystring.
Ah, it wasn't sorted previously either.

```suggestion
- [zustand-querystring](https://github.com/nitedani/zustand-querystring) — A Zustand middleware that syncs the store with the querystring.
- [zustand-rx](https://github.com/patdx/zustand-rx) — A Zustand middleware enabling you to subscribe to a store as an RxJS Observable.
- [zustand-saga](https://github.com/Nowsta/zustand-saga) — A Zustand middleware for redux-saga (minus redux).
- [zustand-store-addons](https://github.com/Diablow/zustand-store-addons) — React state management addons for Zustand.
- [zustand-vue](https://github.com/AwesomeDevin/zustand-vue) - State management for vue (Vue3 / Vue2) based on zustand.   
- [zustand-yjs](https://github.com/tandem-pt/zustand-yjs) — Zustand stores for Yjs structures.
- [zusteller](https://github.com/timkindberg/zusteller) — Your global state savior. "Just hooks" + Zustand.
- [zustood](https://github.com/udecode/zustood) — 🐻‍❄️ A modular store factory using Zustand.
```

2023-02-13 06:01 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
>  - [zustand-saga](https://github.com/Nowsta/zustand-saga) — A Zustand middleware for redux-saga (minus redux).
Ah, it wasn't sorted previously anyway.
```suggestion
- [zustand-querystring](https://github.com/nitedani/zustand-querystring) — A Zustand middleware that syncs the store with the querystring.
- [zustand-rx](https://github.com/patdx/zustand-rx) — A Zustand middleware enabling you to subscribe to a store as an RxJS Observable.
- [zustand-saga](https://github.com/Nowsta/zustand-saga) — A Zustand middleware for redux-saga (minus redux).
```

2023-02-13 06:02 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
>  - [zustand-querystring](https://github.com/nitedani/zustand-querystring) — A Zustand middleware that syncs the store with the querystring.
```suggestion
```

2023-02-13 06:02 UTC, dai-shi commented
Can you adjust them too?

2023-02-13 09:27 UTC, AwesomeDevin commented on docs/integrations/third-party-libraries.md
>  - [zustand-saga](https://github.com/Nowsta/zustand-saga) — A Zustand middleware for redux-saga (minus redux).
> Can you adjust them too?

sure.

2023-02-13 09:33 UTC, AwesomeDevin commented
> Can you adjust them too?

Please review~

2023-02-13 11:43 UTC, dai-shi approved these changes
Thanks for your help!

2023-02-13 13:35 UTC, AwesomeDevin commented
Thank you. I submitted your code

2023-02-13 13:48 UTC, dai-shi commented
Hmmm, not sure what CI is complaining. Can you run `yarn run prettier`?

2023-02-14 02:09 UTC, closed without merging

2023-02-14 02:14 UTC, AwesomeDevin commented
> Hmmm, not sure what CI is complaining. Can you run `yarn run prettier`?

👌