Update demo
pmndrs/zustand pull request #1740
Opened 2023-04-07 07:19 UTC by dbritto-dev

## Related Issues or Discussions

Add support to switch between JavaScript and TypeScript code with a complete example

## Summary

Now you can select between JavaScript or TypeScript code and then copy it

## Check List

- [x] `yarn run prettier` for formatting code and docs

2023-04-09 00:13 UTC, dbritto-dev commented
@dai-shi @sewera would you mind reviewing this?

2023-04-09 10:21 UTC, sewera commented
I'll get around this in a couple of days

2023-04-11 08:42 UTC, sewera requested changes
Apart from this one naming issue, it looks good :)

2023-04-11 08:42 UTC, sewera commented on examples/demo/src/components/CodePreview.js
> +            <CopyLang lang={lang} setLang={setLang} />
I think that "copy-container" and "CopyLang" should be named "snippet-container" and "SnippetLang"; their primary role is to present a code snippet, not be copied :)

2023-04-11 12:43 UTC, dbritto-dev commented
@sewera all yours :D

2023-04-11 12:47 UTC, sewera approved these changes
let's go!

2023-04-11 12:51 UTC, dbritto-dev commented
@dai-shi 🙏

2023-04-11 21:28 UTC, sewera approved these changes
good catch

2023-04-12 00:13 UTC, merged