Update Transient in recipes to match Readme
pmndrs/zustand pull request #1764
Opened 2023-04-21 18:25 UTC by timarney

When looking at the [docs](https://docs.pmnd.rs/zustand/recipes/recipes#transient-updates-(for-frequent-state-changes))  for transient the params for subscribe accept a second arg compared to the repo [Readme](https://github.com/pmndrs/zustand#transient-updates-for-often-occurring-state-changes).

TypeScript also flags the issue

<img width="500" alt="Screen Shot 2023-04-21 at 2 22 07 PM" src="https://user-images.githubusercontent.com/62242/233708497-91aa4c24-cdf2-4462-bb27-98bf86fa8aec.png">

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2023-04-23 07:10 UTC, dbritto-dev approved these changes

2023-04-23 10:46 UTC, dai-shi requested changes
Can you check them please?

2023-04-23 10:46 UTC, dai-shi commented on docs/recipes/recipes.mdx
> +    scratches => (scratchRef.current = scratches)
This looks weird. It has to be:
```suggestion
    (state) => (scratchRef.current = state.scratches)
```

2023-04-23 10:46 UTC, dai-shi commented on docs/recipes/recipes.mdx
>    const scratchRef = useRef(useStore.getState().scratches)
We also want to name it `useScratchStore` instead of `useStore`.

2023-04-24 12:15 UTC, timarney commented
> Can you check them please?

Is that directed at @dbritto-dev ?

2023-04-24 12:29 UTC, dbritto-dev commented
> > Can you check them please?
> 
> Is that directed at @dbritto-dev ?
> 
> 

I guess you need to apply those changes

2023-04-24 13:03 UTC, dbritto-dev approved these changes

2023-04-24 14:29 UTC, merged