Add third party library
pmndrs/zustand pull request #2010
Opened 2023-08-26 12:34 UTC by mayank1513

## Related Issues or Discussions

Fixes #

## Summary

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2023-08-26 19:11 UTC, sewera requested changes

2023-08-26 19:11 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [zustand-sync-tabs](https://www.npmjs.com/package/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin)
Do you have a Github link? It was hard to found quickly from the NPM page, at least for me.

Most if not all links here are repository links, so I think at this point this is what most people expect.

2023-08-27 08:26 UTC, dai-shi commented
Please put GitHub link.

2023-08-27 10:08 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
> +- [zustand-sync-tabs](https://www.npmjs.com/package/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin) [GitHub](https://github.com/maya
Can we do this?
```suggestion
- [zustand-sync-tabs](https://github.com/mayank1513/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin)
```

2023-08-27 13:42 UTC, sewera requested changes

2023-08-27 13:42 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [zustand-sync-tabs](https://github.com/mayank1513/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin)
You can add a full stop at the end and rephrase "SameOrigin" to something like "for apps from the same origin."

```suggestion
- [zustand-sync-tabs](https://github.com/mayank1513/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin).
```

2023-08-28 06:51 UTC, sewera requested changes

2023-08-28 06:51 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [zustand-sync-tabs](https://github.com/mayank1513/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs / windows / iframes (SameOrigin).
Just like in a previous PR:

```suggestion
- [zustand-sync-tabs](https://github.com/mayank1513/zustand-sync-tabs) — Zustand middleware to easily sync Zustand state between tabs/windows/iframes with same origin.
```

2023-08-28 22:27 UTC, merged