Persist and sync
pmndrs/zustand pull request #2011
Opened 2023-08-26 12:44 UTC by mayank1513

## Related Issues or Discussions

Fixes #

## Summary

Added third party integration

- [persist-and-sync](https://www.npmjs.com/package/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (Same Origin)

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2023-08-26 19:15 UTC, sewera requested changes

2023-08-26 19:15 UTC, sewera commented on .gitignore
> +*lock*
`yarn.lock` file is and should remain tracked by Git

2023-08-26 19:15 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [persist-and-sync](https://www.npmjs.com/package/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (SameOrigin)
Do you have a Github link for it?

2023-08-27 05:59 UTC, mayank1513 commented on docs/integrations/third-party-libraries.md
> +- [persist-and-sync](https://www.npmjs.com/package/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (SameOrigin)
Added GitHub link and also updated npm

2023-08-27 08:16 UTC, dai-shi commented
Please don't modify .gitignore in this PR.

2023-08-27 08:27 UTC, mayank1513 commented
> Please don't modify .gitignore in this PR.

ok. So, you want me to create separate PR for .gitignore?

2023-08-27 08:46 UTC, dai-shi commented
Sorry for the confusion. At this point, I don't think we need to modify .gitignore. If you want to discuss, you may want to open a new discussion first.

2023-08-27 10:41 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
> +- [persist-and-sync](https://github.com/mayank1513/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (SameOrigin) ![npm bundle size](htt
Let's make it consistent with others.
```suggestion
- [persist-and-sync](https://github.com/mayank1513/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (SameOrigin)
```

2023-08-27 15:17 UTC, sewera requested changes
You can also add this library to the previous PR so that your changes are all in one place if you want.

2023-08-27 15:17 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [persist-and-sync](https://github.com/mayank1513/persist-and-sync) - Zustand middleware to easily persist and sync Zustand state between tabs / windows / iframes (SameOrigin)
You can add a full stop at the end and rephrase "SameOrigin" to something like "for apps from the same origin."

2023-08-28 06:49 UTC, sewera approved these changes

2023-08-28 06:51 UTC, merged