fix(docs): zustand v3 context migration doc
pmndrs/zustand pull request #2039
Opened 2023-09-10 03:41 UTC by dai-shi

## Related Issues or Discussions

Fixes https://github.com/pmndrs/zustand/discussions/1276#discussioncomment-6953472

## Summary

The migration doc was misguiding.

## Check List

- [x] `yarn run prettier` for formatting code and docs

2023-09-10 18:56 UTC, sewera requested changes

2023-09-10 18:56 UTC, sewera commented on docs/previous-versions/zustand-v3-create-context.md
> +Or, reach out some third-party libraries that provide Zustand v3-like APIs:
```suggestion
Or reach out to some third-party libraries that provide Zustand v3-like APIs:
```

2023-09-10 18:56 UTC, sewera commented on docs/previous-versions/zustand-v3-create-context.md
> +- https://github.com/charkour/zustand-di
```suggestion
- <https://github.com/charkour/zustand-di>
```

2023-09-10 18:56 UTC, sewera commented on docs/previous-versions/zustand-v3-create-context.md
> +- https://github.com/arvinxx/zustand-utils
```suggestion
- <https://github.com/arvinxx/zustand-utils>
```

2023-09-10 18:56 UTC, sewera commented on docs/previous-versions/zustand-v3-create-context.md
> +- https://github.com/charkour/zustand-di
These angle brackets are the standard way of creating hyperlinks: <https://github.github.com/gfm/#autolinks>

2023-09-11 00:50 UTC, dai-shi commented
@sewera Thanks!!

2023-09-11 09:27 UTC, mayank1513 approved these changes

2023-09-11 09:29 UTC, sewera approved these changes

2023-09-11 09:42 UTC, merged