Extract shallow vanilla
pmndrs/zustand pull request #2097
Opened 2023-10-03 18:08 UTC by dbritto-dev

## Related Issues or Discussions

Fix https://github.com/pmndrs/zustand/discussions/2095

## Summary

- Split shallow in two modules `zustand/shallow` and `zustand/shallow/vanilla`
- Split tests for vanilla and react version

## Check List

- [x] `yarn run prettier` for formatting code and docs

2023-10-03 18:15 UTC, dbritto-dev commented
@dai-shi here you go

2023-10-03 23:32 UTC, dai-shi requested changes
`tests/vanilla/shadow.test.tsx` -> `tests/vanilla/shallow.test.tsx` ?
(Not sure if I prefer the folder structure under tests, but I know what you want.)

We also need to change package.json. Please create `./shallow/react` entry point. (see how `./middleware/immer` is defined.

2023-10-04 04:04 UTC, dbritto-dev commented
> `tests/vanilla/shadow.test.tsx` -> `tests/vanilla/shallow.test.tsx` ? (Not sure if I prefer the folder structure under tests, but I know what you want.)
> 
> We also need to change package.json. Please create `./shallow/react` entry point. (see how `./middleware/immer` is defined.

@dai-shi about folder sturcture I'm following the structure on jotai tests

2023-10-04 04:46 UTC, dbritto-dev commented
@dai-shi all yours, keep me in the loop

2023-10-04 05:01 UTC, dai-shi commented
> about folder structure under tests I'm following the structure on jotai tests

wait, I think I misunderstood the jotai structure for "src" too.
if we were to follow it, it will be:
- `zustand/shallow`
- `zustand/vanilla/shallow`
- `zustand/react/shallow`

What do you think?

2023-10-04 05:13 UTC, dbritto-dev commented
@dai-shi sounds good to me let me update it to match the src structure too

2023-10-04 10:28 UTC, dai-shi reviewed
Thanks for the revision. Looks good overall. See the comments.

2023-10-04 10:28 UTC, dai-shi commented on src/vanilla/shallow.ts
> +}) as typeof shallow
Please move this to `src/shallow.ts`.

2023-10-04 10:28 UTC, dai-shi commented on src/shallow.ts
> +export { useShallow } from './react/shallow.ts'
The whole point is to avoid this in v4.
```suggestion

// We will export this in v5
// export { useShallow } from './react/shallow.ts'
```

2023-10-04 16:14 UTC, dbritto-dev commented
@dai-shi all yours, keep me in the loop

2023-10-04 23:23 UTC, dai-shi reviewed
The code looks good.
Can you try creating a codesandbox example? It should fail.
We need to add two build scripts like this:
```
"build:vanilla:shallow": "rollup -c --config-vanilla_shallow",
"build:react:shallow": "rollup -c --config-react_shallow",
```
and the codesandbox example should work.

2023-10-05 11:06 UTC, dai-shi commented
This doesn't work:
https://codesandbox.io/s/react-typescript-forked-y24k6g fb8b211

But, this does work:
https://codesandbox.io/s/react-typescript-forked-khknwm 223c67f

2023-10-05 11:07 UTC, dai-shi approved these changes

2023-10-05 14:04 UTC, merged