Errors and types fix for URL state exxample
pmndrs/zustand pull request #2218
Opened 2023-11-28 00:58 UTC by CodyCodes95

## Related Issues or Discussions
NA
Fixes #

Resolved a few errors and type errors in the persist and create state with URL example:

1. createJsonStorage not being called in storageOptions resulting in a type error.
2. Correct hook not being exported
3. Moved the creation of initial state inline to get the correct types passed from create/persist.
4. Used state type as generic for persist.

## Summary

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2023-11-28 01:39 UTC, dbritto-dev requested changes
Please review the suggestions

2023-11-28 01:39 UTC, dbritto-dev commented on docs/guides/connect-to-state-with-url-hash.md
> +
```suggestion
        set((state) => ({ typesOfFish: [...state.typesOfFish, fishType] })),
```

2023-11-28 01:39 UTC, dbritto-dev commented on docs/guides/connect-to-state-with-url-hash.md
> +        set(() => ({ numberOfBears: newNumber })),
```suggestion
      setNumberOfBears: (numberOfBears) =>
        set(() => ({ numberOfBears })),
```

2023-11-28 07:00 UTC, CodyCodes95 commented
> Please review the suggestions

Thankyou! Made a commit with your suggestions.

2023-11-28 08:53 UTC, sewera commented
Hi, unfortunately I won't be able to review PRs this week because of illness :(

2023-11-28 09:26 UTC, dai-shi commented
Please take care.

2023-12-09 03:34 UTC, dai-shi commented
@dbritto-dev Can you review it please?

2023-12-09 12:03 UTC, dbritto-dev commented
@dai-shi sure I'll take care

2023-12-31 12:49 UTC, dbritto-dev approved these changes

2023-12-31 13:29 UTC, merged