docs: adding note about middlewares and slices
pmndrs/zustand pull request #2378
Opened 2024-02-29 17:12 UTC by Cadienvan

## Related Issues or Discussions

Fixes #2376.

## Summary

As mentioned, I started adding a note to discuss with @dbritto-dev about using middlewares in slices.

## Check List

- [x] `yarn run prettier` for formatting code and docs

2024-02-29 17:13 UTC, Cadienvan commented
@dbritto-dev let me know which wording you'd prefer to use, I started by applying a simple phrase, feel free to update it!

2024-02-29 17:47 UTC, dbritto-dev commented
@Cadienvan LGTM

2024-03-01 01:21 UTC, dai-shi reviewed
👍

2024-03-01 12:13 UTC, sewera requested changes

2024-03-01 12:13 UTC, sewera commented on docs/guides/slices-pattern.md
> +Please, keep in mind you should apply middlewares only in the combined store and avoid applying them inside individual slices to prevent issues.
```suggestion
Please keep in mind you should only apply middlewares in the combined store. Applying them inside individual slices can lead to unexpected issues.
```

2024-03-01 13:03 UTC, Cadienvan commented
@sewera I applied your suggestionm!

2024-03-01 20:23 UTC, dbritto-dev approved these changes

2024-03-01 21:39 UTC, merged