Update third-party-libraries.md
pmndrs/zustand pull request #2435
Opened 2024-03-25 15:11 UTC by DawidWraga

## Related Issues or Discussions

Fixes #

## Summary

Add 3rd party package link

## Check List

- [ ] `yarn run prettier` for formatting code and docs

2024-03-25 23:12 UTC, dai-shi requested changes
Please order it alphabetically.

2024-03-26 13:54 UTC, DawidWraga commented
> Please order it alphabetically.

Thanks for letting me know, I have updated the order.

I have a lot of respect for all your work on Zustand, Valtio and Jotai, thank you for your contributions!

If you have a spare moment I'd love to hear your feedback on the [@davstack/store](https://www.npmjs.com/package/@davstack/storel) api design.

2024-03-26 14:22 UTC, sewera commented on docs/integrations/third-party-libraries.md
> +- [@davstack/store](https://www.npmjs.com/package/@davstack/store) - A zustand store factory that auto generates selectors with get/set/use methods, supports inferred types, and makes global / local
```suggestion
- [@davstack/store](https://www.npmjs.com/package/@davstack/store) — A zustand store factory that auto generates selectors with get/set/use methods, supports inferred types, and makes global / local state management easy.
```

2024-03-26 23:54 UTC, dai-shi approved these changes
Thanks!

2024-03-26 23:54 UTC, merged