[Zustand Docs] Add third party library `zustand-async-slice`
pmndrs/zustand pull request #2730
Opened 2024-09-10 07:26 UTC by mym0404

Hello, I read [contributing guide](https://github.com/pmndrs/zustand/blob/main/CONTRIBUTING.md). However, the main branch of `website` is missing and I can't find proper way.

## Summary

Add `zustand-async-slice` package into zustand third party library listing.

## Check List

- [x] `pnpm run prettier` for formatting code and docs

2024-09-10 11:07 UTC, dai-shi commented
contributing guide seems outdated... cc @dbritto-dev ?

2024-09-10 11:07 UTC, dai-shi requested changes
Please reorder.

2024-09-10 11:07 UTC, dai-shi commented on docs/integrations/third-party-libraries.md
> +- [zustand-async-slice](https://github.com/mym0404/zustand-async-slice) - Simple Zustand utility to create Async Slice. TypeScript Fully Supported 🖖
We order this list alphabetically.

2024-09-10 11:23 UTC, mym0404 commented on docs/integrations/third-party-libraries.md
> +- [zustand-async-slice](https://github.com/mym0404/zustand-async-slice) - Simple Zustand utility to create Async Slice. TypeScript Fully Supported 🖖
Sure.

2024-09-11 01:14 UTC, dai-shi approved these changes
👍

2024-09-11 01:19 UTC, merged