docs: logo optimization and adding alt
pmndrs/zustand pull request #2784
Opened 2024-10-11 22:27 UTC by Amyssyko

The JPG image has been replaced with an AVIF version, which offers better compression and faster loading times, AVIF (which is supported by 92.64% of browsers worldwide according to [caniuse](https://caniuse.com/avif)). This optimizes page performance without compromising compatibility or image quality.

2024-10-11 23:19 UTC, dai-shi requested changes
Just leave the image file unchanged for now. ALT seems good.

2024-10-12 01:50 UTC, Amyssyko commented
I understand the request to keep the current image. To implement the alt text and also improve performance with AVIF, we could use the following structure:
```js
<div class="flex justify-center mb-4">
  <picture>
    <source srcset="../bear.avif" type="image/avif" />
    <img src="../bear.jpg" alt="Logo Zustand" />
  </picture>
</div>
```
Keep the image used as a fallback and optimize it

2024-10-12 02:21 UTC, dai-shi commented
I understand your suggestion, thanks. But, let's just leave it.

2024-10-12 03:21 UTC, dai-shi commented on docs/getting-started/introduction.md
> +    <img src="../bear.jpg" alt="Logo Zustand" />
```suggestion
  <img src="../bear.jpg" alt="Logo Zustand" />
```

2024-10-12 03:24 UTC, dai-shi approved these changes
thx!

2024-10-12 03:24 UTC, merged