Add `trace` property to devtools options
pmndrs/zustand pull request #752
Opened 2022-01-13 03:31 UTC by DanielPower

Relates to #716

From my testing, redux dev tools trace feature is already working without any changes on Zustand's side. All that's necessary is to type the option so that Typescript will allow it to be passed.

There is at least one caveat, and that is that if you try to use a callback for trace, it does not correctly get passed the action as an argument. This functionality exists so you can either customize the trace, or to conditionally trace on some actions like in the example below.
```
trace: (action) => {
  if (shouldTrace(action)) {
    return new Error().trace;
  }
},
```

In this example, `action` will always come back as `undefined`. I intend to look into this and will put up another PR when I can with the necessary fixes. However as an initial step, I'm putting up this PR to type the field, because much of the functionality is already working.

2022-01-13 15:45 UTC, DanielPower commented on src/middleware/devtools.ts
> +type DevtoolsOptionsType = {
I saw `DevtoolsType`, and tried to be consistent with existing code. But I prefer calling it just `DevtoolsOptions` as well. Resolved :)

2022-01-14 13:02 UTC, devanshj commented on src/middleware/devtools.ts
> +  }
Are you sure we don't need any changes in our implementation to support these flags? Are these entirely handled by the extension? And could point to the type definition of this from the [repo](https://github.com/reduxjs/redux-devtools). We should also include jsdoc for them.

You can opt to remove `features` altogether, no issues, I just don't want to do things half-baked :)

2022-01-14 13:03 UTC, devanshj commented on src/middleware/devtools.ts
> +  trace?: boolean | (() => string)
Let's remove `(() => string)` if it's not working. (I assume we need to change our implementation to support it?)

2022-01-14 13:04 UTC, devanshj commented on src/middleware/devtools.ts
> +  traceLimit?: number
The following applies to `trace` and `traceLimit` too

> Are you sure we don't need any changes in our implementation to support these flags? Are these entirely handled by the extension? And could point to the type definition of this from the repo. We should also include jsdoc for them.

2022-01-14 13:06 UTC, devanshj commented on src/middleware/devtools.ts
> +type DevtoolsOptions = {
If you're interested you can look up the [repo](https://github.com/reduxjs/redux-devtools), find out what other options we're missing that don't require implementation changes and add jsdocs for the them and the existing ones too

2022-01-24 07:08 UTC, dai-shi requested changes
Please consider @devanshj's comments.

2022-01-24 13:53 UTC, DanielPower commented
Thank you for the comments. Will loop back to this as soon as I can.

2022-04-18 02:17 UTC, dai-shi commented
Closing this as stale. Please start over because we have many changes in the main branch. #716 should be the issue for tracking and discussion.

2022-04-18 02:17 UTC, closed without merging